### ISSUE TITLE
Trouble building 32bit binaries with 64bit machine

### ISSUE THREAD

**Issue by joywelt** [steinwurf/waf-tools#85]
For some reason I have to configure with the option --cxxflags="-m32", but when I add it, then it always fail to find the library pthread. Without this option everything is working fine. Could this problem come from the waf tool?

**Comment by petya2164** [comment]
@joywelt Sorry, but we do not use the issue tracker. 
If you have any questions or suggestions about our software, please contact us at our developer mailing list (hosted at Google Groups): http://groups.google.com/group/steinwurf-dev
In any case, we need more details for a bug report and you should always start with your motivation.
